#!/usr/bin/env perl

use Mojolicious::Lite;
use Flickr::API2;
use Data::Dumper;

# flickr key: 76904a42e0e0a2b7eeaf037c8ec2e00b
# flickr secret: b4d1a53c3463051a
my $flickr = new Flickr::API2({'key' => '76904a42e0e0a2b7eeaf037c8ec2e00b', 'secret' => 'b4d1a53c3463051a'});

get '/' => sub {
    my $self = shift;
    $self->render('index');
};

get '/perl/about' => sub {
    my $self = shift;
    $self->render('about');
};

get '/perl/contact' => sub {
    my $self = shift;
    $self->render('contact');
};

get '/perl/' => sub {
    my $self = shift;
    $self->render('index');
};

sub get_image_list {
    my ($lat, $lon, $size) = @_;
    my $images = $flickr->execute_method(
	'flickr.photos.search', {
	    lat => $lat,
	    lon => $lon,
	    min_taken_date => 1262304000,
	    accuracy => 3,
	    has_geo => 1,
	}
    );

    #print STDERR Dumper($images);
    my $res;
    my @urls = map {
	'http://farm'.$_->{farm}.'.static.flickr.com/'
		.$_->{server}.'/'.$_->{id}
			.'_'.$_->{secret}.'_'.$size.'.jpg'
		    } (@{$images->{photos}->{photo}});

    return @urls;
}

get '/perl/find/(*lat)/(*lon)' => sub {
    my $self = shift;
    my $lat  = $self->stash('lat');
    my $lon  = $self->stash('lon');

    $self->render_text(
	join "", map { "<img src='$_'/>" } get_image_list($lat, $lon, "t")
    );
};

app->start;
