#!/usr/bin/env perl

use Mojolicious::Lite;
use Flickr::API2;
use Data::Dumper;

# flickr key: 76904a42e0e0a2b7eeaf037c8ec2e00b
# flickr secret: b4d1a53c3463051a
my $flickr = new Flickr::API2({'key' => '76904a42e0e0a2b7eeaf037c8ec2e00b', 'secret' => 'b4d1a53c3463051a'});

get '/' => sub {
    my $self = shift;
    $self->render('index');
};

get '/perl/about' => sub {
    my $self = shift;
    $self->render('about');
};

get '/perl/contact' => sub {
    my $self = shift;
    $self->render('contact');
};

get '/perl/' => sub {
    my $self = shift;
    $self->render('index');
};

get '/perl/find/(*lat)/(*lon)' => sub {
    my $self = shift;
    my $lat  = $self->stash('lat');
    my $lon  = $self->stash('lon');

    my $images = $flickr->execute_method('flickr.photos.search', {
            lat => $lat,
            lon => $lon,
            min_taken_date => 1262304000,
            accuracy => 3,
            has_geo => 1,
        }
    );

    #print STDERR Dumper($images);

    my $res;
    foreach my $img (@{$images->{photos}->{photo}}){
        my $url = 'http://farm'.$img->{farm}.'.static.flickr.com/'.$img->{server}.'/'.$img->{id}.'_'.$img->{secret}.'_t.jpg';
        $res .= '<img src="'.$url.'" />';
    }
    $self->render_text($res);
};


app->start;
